-- WimpSchool Supabase schema definitions

create table if not exists schools (
  id bigint generated by default as identity primary key,
  name text not null,
  address text,
  school_code text unique not null,
  subscription_plan text,
  pending_subscription_plan text,
  subscription_change_effective_date timestamptz,
  admin_id uuid references auth.users(id),
  verified boolean default false,
  created_at timestamptz default timezone('utc', now())
);

create table if not exists user_roles (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) not null,
  school_id bigint references schools(id),
  role text not null,
  created_at timestamptz default timezone('utc', now())
);

create table if not exists teachers (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id),
  school_id bigint references schools(id) not null,
  name text not null,
  email text not null,
  subjects text,
  classes text,
  invite_token text unique,
  account_created boolean default false,
  created_at timestamptz default timezone('utc', now())
);

create table if not exists students (
  id bigint generated by default as identity primary key,
  school_id bigint references schools(id) not null,
  name text not null,
  student_code text unique not null,
  class_name text,
  parent_email text,
  assigned_teacher_id bigint references teachers(id),
  created_at timestamptz default timezone('utc', now())
);

create table if not exists parents (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id),
  school_id bigint references schools(id) not null,
  name text not null,
  email text not null,
  phone text,
  student_id bigint references students(id),
  invite_token text unique,
  account_created boolean default false,
  created_at timestamptz default timezone('utc', now())
);

create table if not exists attendance (
  id bigint generated by default as identity primary key,
  school_id bigint references schools(id) not null,
  student_id bigint references students(id) not null,
  teacher_id bigint references teachers(id),
  class text,
  status text check (status in ('present', 'absent', 'late', 'excused')),
  recorded_at timestamptz default timezone('utc', now())
);

create table if not exists results (
  id bigint generated by default as identity primary key,
  school_id bigint references schools(id) not null,
  student_id bigint references students(id) not null,
  teacher_id bigint references teachers(id),
  subject text not null,
  score numeric,
  term text,
  submitted boolean default false,
  submitted_at timestamptz default timezone('utc', now())
);

create table if not exists payments (
  id bigint generated by default as identity primary key,
  school_id bigint references schools(id) not null,
  student_id bigint references students(id),
  parent_id bigint references parents(id),
  amount numeric not null,
  status text check (status in ('pending', 'paid', 'failed', 'refunded')) default 'pending',
  method text,
  tx_ref text unique,
  processed_at timestamptz,
  created_at timestamptz default timezone('utc', now())
);

create table if not exists announcements (
  id bigint generated by default as identity primary key,
  school_id bigint references schools(id) not null,
  title text not null,
  body text not null,
  target_class text default 'all',
  created_at timestamptz default timezone('utc', now())
);

create table if not exists notifications (
  id bigint generated by default as identity primary key,
  school_id bigint references schools(id),
  user_id uuid references auth.users(id),
  type text,
  message text,
  read boolean default false,
  created_at timestamptz default timezone('utc', now())
);
